# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    proxmox = {
      source  = "thegameprofi/proxmox"
      version = ">= 2.9.15"
    }
    ansible = {
      source  = "ansible/ansible"
      version = ">= 1.1.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.0.0"
    }
    infisical = {
      source  = "infisical/infisical"
      version = ">= 0.3.2"
    }
    vault = {
      source  = "hashicorp/vault"
      version = ">= 3.23.0"
    }
    influxdb-v2 = {
      source  = "pranjalv123/influxdb-v2"
      version = ">= 0.4.10"
    }
  }
}


provider "nomad" {
  address = "https://nomad-server-a:4646"
}

provider "infisical" {
  host          = "http://infisical.svc.43mar.io"
  service_token = jsondecode(data.aws_secretsmanager_secret_version.infisical.secret_string).SERVICE_TOKEN
}

provider "vault" {
  address = "https://vault.43mar.io:8200"
  skip_tls_verify = true
}

provider "proxmox" {
  pm_api_url = "https://proxmox:8006/api2/json"
  pm_user    = "root@pam!terraform"

  pm_api_token_id = "terraform@pam!terraform"
  pm_api_token_secret = data.aws_secretsmanager_secret_version.proxmox_login.secret_string

  pm_tls_insecure = true

  pm_log_enable = true
  pm_log_file   = "/tmp/terraform-plugin-proxmox.log"
  pm_debug      = true
  pm_log_levels = {
    _default    = "debug"
    _capturelog = ""
  }
}

#
#data "vault_kv_secret_v2" "influxdb_key" {
#  mount = "kv"
#  name = "influxdb/root_token"
#}
#provider "influxdb-v2" {
#  token = data.vault_kv_secret_v2.influxdb_key.data["token"]
#  url   = "https://influxdb.svc.43mar.io/"
#}
#
#data "influxdb-v2_organization" "o43mario" {
#  name = "43mar.io"
#}

data "aws_secretsmanager_secret" "infisical" {
  name = "infisical" # As stored in the AWS Secrets Manager
}
data "aws_secretsmanager_secret_version" "infisical" {
  secret_id = data.aws_secretsmanager_secret.infisical.id
}

data "aws_secretsmanager_secret" "proxmox_login" {
  name = "proxmox/terraform" # As stored in the AWS Secrets Manager
}
data "aws_secretsmanager_secret_version" "proxmox_login" {
  secret_id = data.aws_secretsmanager_secret.proxmox_login.id
}
